# Generated by Django 4.2.10 on 2026-05-18 07:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nrc', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('has_carry_courses', models.BooleanField(default=False, help_text='Does the student have carry-over courses?')),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Graduated', 'Graduated')], default='Active', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='api_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='api_user_set', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('upschool', 'Up-School'), ('downschool', 'Down-School'), ('freshers', 'Freshers Compound')], max_length=20)),
                ('type', models.CharField(choices=[('hostel', 'Hostel'), ('sabbatical', 'Sabbatical House')], default='hostel', max_length=20)),
                ('gender_policy', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('total_capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='OffCampusHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('gender_policy', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('total_bedspaces', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offcampus/')),
                ('description', models.TextField(blank=True)),
                ('landlord_name', models.CharField(blank=True, max_length=200)),
                ('landlord_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'off_campus_houses',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=2)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hostel')),
            ],
            options={
                'db_table': 'rooms',
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='OffCampusRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=1)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.offcampushouse')),
            ],
            options={
                'db_table': 'off_campus_rooms',
                'unique_together': {('house', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('on-campus', 'On-Campus'), ('off-campus', 'Off-Campus')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('offer_sent_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('offer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('preferred_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hostel')),
                ('preferred_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.offcampushouse')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('completed', 'Completed')], default='active', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='api.application')),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hostel')),
                ('off_campus_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.offcampushouse')),
                ('off_campus_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.offcampusroom')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allocations',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('revoke', 'Revoke'), ('allocate', 'Allocate'), ('accept', 'Accept'), ('decline', 'Decline'), ('test', 'Test')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
